name: Build firmware

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /
    branches:
      - 'master'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: ls
      run: ls

    - name: Configure CMake
      run: |
        mkdir -p firmware/build
        cd firmware/build
        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..

    - name: Build
      run: |
        cd firmware/build
        make
